export const UPDATE_SCORE = 'UPDATE_SCORE';
export const TOGGLE_SHOW_CARDS = 'TOGGLE_SHOW_CARDS';
export const UPDATE_NAME = 'UPDATE_NAME';

export const API = {
  OPEN_CONNECTION:{
    START: 'API.OPEN_CONNECTION.START',
    SUCCESS: 'API.OPEN_CONNECTION.SUCCESS',
    FAILURE: 'API.OPEN_CONNECTION.FAILURE',
  },
}
