export const UPDATE_SCORE = 'UPDATE_SCORE'
export const TOGGLE_SHOW_CARDS = 'TOGGLE_SHOW_CARDS'
export const UPDATE_NAME = 'UPDATE_NAME'
export const UPDATE_EVERYTHING ='UPDATE_EVERYTHING'

export const API = {
  OPEN_CONNECTION:{
    START: 'API.OPEN_CONNECTION.START',
    SUCCESS: 'API.OPEN_CONNECTION.SUCCESS',
    FAILURE: 'API.OPEN_CONNECTION.FAILURE',
  },
  UPDATE_SCORE:{
    START: 'API.UPDATE_SCORE.START',
    SUCCESS: 'API.UPDATE_SCORE.SUCCESS',
    FAILURE: 'API.UPDATE_SCORE.FAILURE',
  },
  UPDATE_NAME:{
    START: 'API.UPDATE_NAME.START',
    SUCCESS: 'API.UPDATE_NAME.SUCCESS',
    FAILURE: 'API.UPDATE_NAME.FAILURE',
  },
  CARD_VISIBILITY:{
    START: 'API.CARD_VISIBILITY.START',
    SUCCESS: 'API.CARD_VISIBILITY.SUCCESS',
    FAILURE: 'API.CARD_VISIBILITY.FAILURE',
  },
  RESET_SCORES:{
    START: 'API.RESET_SCORES.START',
    SUCCESS: 'API.RESET_SCORES.SUCCESS',
    FAILURE: 'API.RESET_SCORES.FAILURE',
  }
}
