const EVENT_JOIN = 'join'
const EVENT_UPDATE_SCORE = 'EVENT_UPDATE_SCORE'
const EVENT_UPDATE_NAME = 'EVENT_UPDATE_NAME'
const EVENT_NEW_PLAYER = 'EVENT_NEW_PLAYER'
const EVENT_REFRESH = 'EVENT_REFRESH'

module.exports = {
  EVENT_UPDATE_SCORE,
  EVENT_UPDATE_NAME,
  EVENT_NEW_PLAYER,
  EVENT_REFRESH,
}
